# Generated by Django 4.1.7 on 2023-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategories',
            name='token',
            field=models.CharField(default='wiebcwpec', max_length=50),
            preserve_default=False,
        ),
    ]
