# Generated by Django 3.2.19 on 2023-05-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0002_auto_20230517_1755'),
        ('ami_test_web_app', '0002_usercategories_token'),
    ]

    operations = [
    ]
