# Generated by Django 3.2.19 on 2023-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0004_auto_20230519_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatives',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='initiative',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='tieBackToCurrentStateFindings',
            field=models.TextField(),
        ),
    ]
