# Generated by Django 4.1.7 on 2023-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0006_rename_fullname_userinfo_firstname_userinfo_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='confirm_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
