# Generated by Django 4.1.7 on 2023-06-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0007_userinfo_confirm_password_userinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('is_objective', models.BooleanField()),
                ('answer', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.questions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.userinfo')),
            ],
        ),
    ]
