# Generated by Django 4.1.7 on 2023-06-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0008_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='answer',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='is_objective',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question_id',
        ),
    ]
