# Generated by Django 4.2.3 on 2023-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0009_rename_answer_userresponse_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='project',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
