# Generated by Django 4.2.3 on 2023-07-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0010_userinfo_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.org')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.org'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.project'),
        ),
    ]
