# Generated by Django 4.2.3 on 2023-07-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0011_org_project_alter_userinfo_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='poc_email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='poc_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='poc_role',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
