# Generated by Django 4.2.3 on 2023-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0012_org_poc_email_org_poc_name_org_poc_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='project',
            field=models.CharField(max_length=50),
        ),
    ]
