# Generated by Django 4.2.3 on 2023-08-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0016_alter_userinfo_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='fullname',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='middlename',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
