# Generated by Django 4.2.3 on 2023-09-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0017_remove_userinfo_fullname_userinfo_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ans_type',
            field=models.CharField(choices=[('radio', 'Radiobutton'), ('text', 'Textbox'), ('upload', 'Upload'), ('checkbox', 'Checkbox')], default='Radiobutton', max_length=50),
        ),
        migrations.CreateModel(
            name='InitiativeTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiatives', models.CharField(max_length=5000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.categories')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.dimensions')),
            ],
        ),
    ]
