# Generated by Django 4.2.3 on 2023-09-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0018_alter_questions_ans_type_initiativetraceability'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_id', models.CharField(max_length=20)),
                ('initiative', models.TextField()),
                ('description', models.TextField()),
                ('tieback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='initiativetraceability',
            name='initiatives',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Initiatives',
        ),
    ]
