# Generated by Django 4.2.3 on 2023-09-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0020_rename_firstname_userinfo_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('admin', 'QE Admin'), ('user', 'QE User'), ('tester', 'QE Tester')], default='QE Admin', max_length=50),
        ),
    ]
