# Generated by Django 4.2.3 on 2023-09-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0021_alter_userinfo_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInitiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.userinfo')),
            ],
        ),
    ]
