# Generated by Django 4.2.3 on 2023-09-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0022_finalinitiatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativedetail',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiativedetail',
            name='dimension',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.dimensions'),
            preserve_default=False,
        ),
    ]
