# Generated by Django 4.2.3 on 2023-09-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0023_initiativedetail_category_initiativedetail_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_objective',
        ),
    ]
