# Generated by Django 4.2.3 on 2023-09-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0024_remove_questions_is_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='criteria',
        ),
    ]
