# Generated by Django 4.2.3 on 2023-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0025_remove_questions_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ans_type',
            field=models.CharField(choices=[('Radiobutton', 'Radiobutton'), ('Textbox', 'Textbox'), ('Upload', 'Upload'), ('Checkbox', 'Checkbox')], default='Radiobutton', max_length=50),
        ),
    ]
