# Generated by Django 4.2.3 on 2023-09-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0027_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
