# Generated by Django 4.2.3 on 2023-10-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0029_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
