# Generated by Django 4.2.3 on 2023-10-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0030_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=300)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.questions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_test_web_app.userinfo')),
            ],
        ),
    ]
