# Generated by Django 4.2.3 on 2023-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0032_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password_change_required',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
