# Generated by Django 4.2.3 on 2023-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_test_web_app', '0033_userinfo_password_change_required_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='weightage',
            field=models.CharField(max_length=10),
        ),
    ]
